### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by Mevrael** [nico3333fr/van11y-accessible-tab-panel-aria#5]
Hi, thank you for your effort in making web accessible and simple. However, achieving this goal is something that requires more resources. Would you mind to join our team, contribute to  https://bunnyjs.com - which makes Vanilla JavaScript simple, great again and help million of users and developers around the world with their problems. You may start by joining our Gitter room.

Are there any other accessible components you would like to have out of the box? Do you have any ideas on how to make JavaScript app development simpler, faster, better and accessible for anyone?

Thanks again.

Best regards,
Mev

**Comment by nico3333fr** [comment]
Hi,

thanks for the suggestion, however, I don't really have a lot of free time. However, if you want ot reuse these components, you can do it, they are placed under MIT license, just need to be quoted, and it will be perfect for me.

Kind rgeards,
Nicolas
