### ISSUE TITLE
Add data-attribute or class to open tab

### ISSUE THREAD

**Issue by hans2103** [nico3333fr/van11y-accessible-tab-panel-aria#6]
Is it possible to add a data-attribute or class to indicate the tab that should be open on page load?
The use case is that not always the first tab should be opened

**Comment by nico3333fr** [comment]
Not yet. It might not be complicated to add it. I'll have a look at it asap ;)

**Comment by nico3333fr** [comment]
This has been added in last commit https://github.com/nico3333fr/van11y-accessible-tab-panel-aria/commit/0387eceea15e7b8b209cfa8c82d4efe42f8f24b1 with the attribute ```data-selected="1"```.

The documentation is updated, see in "Bonuses" on https://van11y.net/accessible-tab-panel/ ;)
or in the https://github.com/nico3333fr/van11y-accessible-tab-panel-aria/blob/master/README.md 

Thanks for the suggestion. 👍
