### ISSUE TITLE
data-selected doesn't seem to work

### ISSUE THREAD

**Issue by hans2103** [nico3333fr/van11y-accessible-tab-panel-aria#8]
Thank you for implementing data-selected with commit 0387ece 
When I open the french demo page I notice the second tab without the second tab active 
I was expecting that the second tab was openend by default. 
https://van11y.net/downloads/tab-panel/demo/index-fr.html

**Comment by nico3333fr** [comment]
Hi,

this is strange, the second tab is opened if I open https://van11y.net/downloads/tab-panel/demo/index-fr.html 
See snapshot, Chrome on the left, Firefox on the right.

![Snasphots](https://user-images.githubusercontent.com/2578321/30584972-ada9ecaa-9d2b-11e7-8a41-800d194aa388.png)

Did you try refreshing your cache, without any fragment in the URL ? (not https://van11y.net/downloads/tab-panel/demo/index-fr.html#id_fourth for example)

**Comment by hans2103** [comment]
that might do the trick... sorry... pebkac

**Comment by nico3333fr** [comment]
No problem ;)
